### ISSUE TITLE
Need to define standard for submitting issues

### ISSUE THREAD

**Issue by neelsmith** [homermultitext/hmt-lexicon#3]
We have good guidelines for submitting issues to repositories like hmt-auth.  We should develop similar guidelines for submitting issues to hmt-lexicon.

What information should editors of HMT texts supply to the managers of the hmt-lexicon when submitting an issue?

Assigning to charlie as a proxy for charlie + claude.

**Comment by cjschu17** [comment]
in the title:  "New addition to Kanones:" then put the word as it would appear in the dictionary and the urn of image citation from where the word in question comes from;

In the body of the text:

surface:  (how the word actually appears in the text)
lexent: (how the word would be found in a dictionary)

I think that should be enough to quickly identify new forms and the lexent helps the lexicon editors quickly check the existing list of lexical entities to see if this form already exists.

**Comment by neelsmith** [comment]
This looks good.  I'll add it to the draft docs for 2016 seminar.  Cc'ing Stephanie for a preview peek at what we'll try in April.

**Comment by neelsmith** [comment]
implemented in issues template.
